### ISSUE TITLE
Cannot see layer names when adding them some in the edition panel

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-plugin#285]
![Screenshot_20200902_121040](https://user-images.githubusercontent.com/1951107/91974895-6d7a0c80-ed16-11ea-8348-c75e6b1c356f.png)

it is only visible the type of geometry, not the name. I'm on Ubuntu 20.04.

**Comment by Gustry** [comment]
Weird, I can't reproduce.
Can you resize the window? Does tooltip works?
Does it happen only on edition tab? Because all tabs now use the same code in the background.

I'm also on Ubuntu 20.04, it works perfectly, QGIS 3.10 and Master.

![Selection_015](https://user-images.githubusercontent.com/1609292/91978299-27c44080-ed24-11ea-8320-5ba49c0904b1.png)

Version de QGIS | 3.10.8-A Coruña | Branche de code de QGIS | Release 3.10
-- | -- | -- | --
Compilé avec Qt | 5.12.8 | Utilisant Qt | 5.12.8
Compilé avec GDAL/OGR | 3.0.4 | Utilisé avec GDAL/OGR | 3.0.4
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
Compilé avec SQLite | 3.31.1 | Fonctionne avec SQLite | 3.31.1
Version du client PostgreSQL | 12.3 (Ubuntu 12.3-1.pgdg20.04+1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.2
Compilé avec PROJ | 6.3.1 | Fonctionne avec PROJ | Rel. 6.3.1, February 10th, 2020
Version de l'OS | Ubuntu 20.04.1 LTS | Cette copie de QGIS dispose d'une sortie de débogage.
Extensions Python actives | quick_map_services; trackable_project_files; lizmap; firstaid; QuickWKT; plugin_reloader; drain_sewer_visual_inspection; gestion_base_adresse; veloroutes_voies_vertes; QuickOSM; MemoryLayerSaver; AsaPerimetre; camino-flux-QGIS-master; french_locator_filter; QgisLayerBoardPlugin; qgis_resource_sharing; db_manager; processing

**Comment by gioman** [comment]
> Can you resize the window?

yes, but does not help



> Does tooltip works?

yes

> Does it happen only on edition tab?

no, you are right, it happens on other tabs too.

> I'm also on Ubuntu 20.04, it works perfectly, QGIS 3.10 and Master.

also using QGIS 3.10, and actually I'm using Kubuntu, so KDE.

**Comment by Gustry** [comment]
AFAIK, nothing has changed on this side of the code for a few months (January 2020). I think.
So it might be related to an upgrade in your environment? (one of Qt, KDE, Kubuntu)
It's a https://qgis.org/api/classQgsMapLayerComboBox.html but only in the plugin. So I expect an difference with the layout containing the combobox.

**Comment by gioman** [comment]
ok, so maybe this should closed a a know issue on certain DE?
