### ISSUE TITLE
[Bug]: Changes made in layout tab are not saved

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-plugin#493]
### What is the bug?

Changing layout parameters (e.g. formats, DPI, etc.) in the layout tab has no effect on Lizmap Web Client. After checking, changes are not saved. When opening again the Lizmap extension the  changes made previously in the layout tab have not been saved. They have been restored to their previous state (all options).

Step 1 - Change DPI and formats. then close Lizmap window.
![image](https://user-images.githubusercontent.com/425243/233272618-b8ef0914-201a-4f18-b303-b91f07fb6570.png)

Step 2 - Go Back to Lizmap Window. Parameters have been restored (all formats, all DPI, etc.)
![image](https://user-images.githubusercontent.com/425243/233272762-9c3d1c50-d262-4526-8c7e-9598b8c84c18.png)

### Versions

**Versions :**

* Lizmap Web Client : 3.6.3
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.11.5
* QGIS Desktop : 3.26.3
* QGIS Server : 3.22.7
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : not found

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by Gustry** [comment]
> Lizmap Web Client target version : 3.6

![](https://wtf.roflcopter.fr/pics/ZjHJamdU/emTut8e8)

This whole panel is designed for Lizmap Web Client 3.7.
I will make it more clear.

**Comment by arno974** [comment]
Is there already a 3.7 Lizmap web client available ? I didn't find it on the github repo.
It might require a lot of changes, but maybe automatically hide the options not available depending on the lizmap web version ?

**Comment by Gustry** [comment]
> Is there already a 3.7 Lizmap web client available ?

There are ZIP produced after each commit for each branch : 3.5, 3.6 and 3.7 https://packages.3liz.org/
No official tag for now on GitHub release.

> It might require a lot of changes, but maybe automatically hide the options not available depending on the lizmap web version ?

I understand your point. It would make sense for some options indeed.

But it's also a way for us to promote, make some teasing about new features. I agree LWC 3.7 is in a early stage for now...

If someone has a lot of blue things on his screen (because he is running LWC 3.3 :D ), it would encourage him to upgrade to newest release as soon as to **unlock** features.
