### ISSUE TITLE
Identify layers by name leads to major configuration losses

### ISSUE THREAD

**Issue by haubourg** [3liz/lizmap-plugin#53]
Hi, 
when renaming a layer in QGIS, all its configuration is lost. Pop html - css template can be a lot of work. 
Identifying layers be their ID's would give lot more stable configurations and less work to Lizmap administrators. 
I think #42  is related too 
Cheers

**Comment by mdouchin** [comment]
In fact, I have always wanted to use layerId instead, but since we can also configure groups in the Layers panel, we chose to use the name instead.
Since QGIS 2.14, groups and layers can now have a "shortname". We will have a deep thinking of how to avoid renaming issue.

Note that you could also use QGIS maptip to configure the popup content, and use expressions. In latest Lizmap Web Client and lizmap plugin (master), the editor can choose the source of popup for each layer or group among : auto, lizmap and qgis See fe394b3979bfd55a3067d131ec06e7d259b79405

**Comment by haubourg** [comment]
Thanks for the hint!

**Comment by pcav** [comment]
I think it would be worth to keep this alive.

**Comment by Gustry** [comment]
Maybe I'm missing some history, but layer name is not used anymore in Lizmap.
Any configuration still using layer name @pcav ?

**Comment by pcav** [comment]
Do you imply that renaming a layer does not have an effect on Lizmap? If so, sorry about the noise, please close this.
